### ISSUE TITLE
catch doesn't work with 1.9.2 and rails 2.3.2.

### ISSUE THREAD

**Issue by celesteking** [cldwalker/debugger#38]
It just fails to work:

``` bash
$ rvm  1.9.2@rails232 do rdebug ./script/console -- --debugger
/storage/personal/work/coding/nventory/server/script/console:2
require File.dirname(__FILE__) + '/../config/boot'
(rdb:1) catch Exception
Catch exception Exception.
(rdb:1) cont
=> Debugger enabled
Loading development environment (Rails 2.3.2)
...
Gem::SourceIndex#initialize called from /estorage/h/f/.rvm/gems/ruby-1.9.2-p320@rails232/gems/rails-2.3.2/lib/rails/vendor_gem_source_index.rb:100.
/estorage/h/f/.rvm/gems/ruby-1.9.2-p320@rails232/gems/rails-2.3.2/lib/rails/gem_dependency.rb:239:in `==': undefined method `name' for "RedCloth":String (NoMethodError)
        from /estorage/h/f/.rvm/rubies/ruby-1.9.2-p320/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb:217:in `==='
        from /estorage/h/f/.rvm/rubies/ruby-1.9.2-p320/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb:217:in `block in matching_specs'

...
$ rvm  1.9.2@rails232 do rdebug ./script/console -- --debugger
/storage/personal/work/coding/nventory/server/script/console:2
require File.dirname(__FILE__) + '/../config/boot'
(rdb:1) show version
ruby-debug 1.2.0
(rdb:1) b gem_dependency.rb:239
*** No source file named gem_dependency.rb
Set breakpoint anyway? (y/n) y
Breakpoint 1 file gem_dependency.rb, line 239
(rdb:1) cont
=> Debugger enabled
Loading development environment (Rails 2.3.2)
...
/estorage/h/f/.rvm/gems/ruby-1.9.2-p320@rails232/gems/rails-2.3.2/lib/rails/gem_dependency.rb:239:in `==': undefined method `name' for "RedCloth":String (NoMethodError)
        from /estorage/h/f/.rvm/rubies/ruby-1.9.2-p320/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb:217:in `==='
        from /estorage/h/f/.rvm/rubies/ruby-1.9.2-p320/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb:217:in `block in matching_specs'

```

Please, fix this. Thanks.
